name: passcode_screen
description: Flutter package to create and verify passcode
version: 1.0.0
author: 'xPutnikx <vladimir.hudnitsky@gmail.com>'
homepage: 'https://github.com/xPutnikx/flutter-passcode'

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0

flutter:
